global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'enterprise-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['enterprise-app:8081']
    scrape_interval: 10s

  - job_name: 'config-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-app:8082']
    scrape_interval: 10s

  - job_name: 'monitor-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitor-app:8083']
    scrape_interval: 10s

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
#  - "alert.rules.yml"